use_frameworks!

target 'ALWCoverBrowser_Example' do
  pod 'ALWCoverBrowser', :path => '../'

  target 'ALWCoverBrowser_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
